export { default as proposal } from './proposal'
export { default as company } from './company'
export { default as person } from './person'
export { default as testimonial } from './testimonial'
export { default as video } from './video'
